name = "{{project_name}}"
client_id = "{{shopify_api_key}}"

[access_scopes]
scopes = "write_products,read_orders"

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/api/webhooks"
